default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: <%= ENV['POSTGRES_POOL'] { 5 } %>
  port: <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV.fetch('POSTGRES_DB') { 'my_finance_api' } %>
  schema_search_path: <%= [ENV.fetch('POSTGRES_SCHEMA') { 'public' }, 'public', 'extensions'].uniq.join(',') %>

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

test:
  <<: *default
  database: my_finance_api_test
  schema_search_path: public
